import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "../globals.css";
import Topbar from "@/components/Hero/Topbar";
import Sidebar from "@/components/Hero/SideBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${poppins.className}`}>
      <body className="h-full bg-[#F4F4F5]  w-full no-scrollbar overflow-auto " style={{ fontFamily: 'Poppins, sans-serif' }}>
        <div className="flex  w-full">
          <div className="w-[19%]">
            <Sidebar />
          </div>
          <div className="w-[81%] ">
            <Topbar />
            <main className="  overflow-y-auto max-h-[calc(100vh-80px)] rounded-3xl   shadow-sm">{children}</main>
          </div>
        </div>

      </body>
    </html>
  );
}
